import { Inter, Modak } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import ClientView from "./ClientView";
import { getProjectBySlug } from "../../lib/proj";
import { CurrentTask } from "../../context/currentTaskContext";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { getProj } from "../../lib/proj";
export default async function RootLayout({ children }) {
  const projects = getProj();

  return (
    <html lang="en">
      <body className={inter.className}>
          <CurrentTask>
            <ClientView projects={projects}>{children}</ClientView>
          </CurrentTask>
      </body>
    </html>
  );
}
