import { Inter, Modak } from "next/font/google";
import "./globals.css";
import SideBar from "./SideBar";
import Header from "./main-header/Header";
const inter = Inter({ subsets: ["latin"] });
import { DndProvider } from "react-dnd";
import { HTML5Backend } from "react-dnd-html5-backend";
import Link from "next/link";
import TopHeader from "./top-header/TopHeader";
import Modal from "./Modal/Modal";
import TaskContext, { CurrentTask } from "../../context/currentTaskContext";
import ClientView from "./ClientView";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { getProj } from "../../lib/proj";
export default function RootLayout({ children }) {
  const projects = getProj();
  return (
    <html lang="en">
      <body className={inter.className}>
        <CurrentTask>

          <ClientView
          projects = {projects}
          >{children}</ClientView>
        </CurrentTask>
      </body>
    </html>
  );
}
